#!/bin/bash

profiles=$(powerprofilesctl list | awk '
    /^[* ][ ]+[a-z-]+:/ {
        profile = substr($2, 1, length($2)-1)
        if ($1 == "*") {
            print profile " (active)"
        } else {
            print substr($1, 1, length($1)-1)
        }
    }
')

selected_profile=$(echo "$profiles" | fzf --prompt="Select a power profile: " --height=10 --layout=reverse)

selected_profile=${selected_profile% (active)}

if [ -n "$selected_profile" ]; then
    powerprofilesctl set "$selected_profile"
    echo "Switched to power profile: $selected_profile"
else
    echo "No profile selected. Exiting."
    exit 0
fi
