import = [
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml",
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 20
padding.y = 20
decorations = "Buttonless"
option_as_alt = "Both"

[font]
normal.family = "JetBrains Mono NF"
normal.style = "Regular"
italic.style = "Regular"
bold.style = "Medium"
offset.y = 5
size = 15
